export const FakePessoa = () => {
    return (
        [
            {
                "id": 3,
                "apto_esocial": "N",
                "id_user": 3097,
                "cpf": "74386735704",
                "nome": "ANA MARIA FERREIRA CUNHA GALVAO",
                "nome_receita": null,
                "nome_social": null,
                "numero_nit_pis_pasep": "12411308762",
                "id_tipo_sexo": 2,
                "id_tipo_identidade_genero": null,
                "id_tipo_raca_cor": null,
                "id_tipo_sanguineo": null,
                "id_tipo_tempo_residencia_imigrante": null,
                "id_tipo_condicao_ingresso_imigrante": null,
                "id_tipo_estado_civil": 2,
                "data_nascimento": "1963-09-25",
                "id_pais_nascimento": null,
                "nome_pai": null,
                "nome_mae": null,
                "data_chegada_brasil": null,
                "numero_registro_estrangeiro": null,
                "data_naturalizacao": null,
                "numero_decreto_naturalizacao": null,
                "data_publicacao_dou_naturalizacao": null,
                "casado_com_nacional": null,
                "possui_filho_brasileiro": null,
                "quantidade_filhos_brasileiros": null,
                "legado": null,
                "id_usuario_criacao": null,
                "id_usuario_atualizacao": null,
                "id_usuario_exclusao": null,
                "ativo": true,
                "deleted_at": null,
                "created_at": "2024-09-23T14:06:28.000000Z",
                "updated_at": "2024-09-23T14:06:28.000000Z",
                "possui_deficiencia": "N",
                "imigrante": "N",
                "mais": [],
                "pais_nascimento": null
            },
            {
              "id": 4,
              "apto_esocial": "N",
              "id_user": 3097,
              "cpf": "74386735704",
              "nome": "FERREIRA CUNHA GALVAO",
              "nome_receita": null,
              "nome_social": null,
              "numero_nit_pis_pasep": "12411308762",
              "id_tipo_sexo": 2,
              "id_tipo_identidade_genero": null,
              "id_tipo_raca_cor": null,
              "id_tipo_sanguineo": null,
              "id_tipo_tempo_residencia_imigrante": null,
              "id_tipo_condicao_ingresso_imigrante": null,
              "id_tipo_estado_civil": 2,
              "data_nascimento": "1963-09-25",
              "id_pais_nascimento": null,
              "nome_pai": null,
              "nome_mae": null,
              "data_chegada_brasil": null,
              "numero_registro_estrangeiro": null,
              "data_naturalizacao": null,
              "numero_decreto_naturalizacao": null,
              "data_publicacao_dou_naturalizacao": null,
              "casado_com_nacional": null,
              "possui_filho_brasileiro": null,
              "quantidade_filhos_brasileiros": null,
              "legado": null,
              "id_usuario_criacao": null,
              "id_usuario_atualizacao": null,
              "id_usuario_exclusao": null,
              "ativo": true,
              "deleted_at": null,
              "created_at": "2024-09-23T14:06:28.000000Z",
              "updated_at": "2024-09-23T14:06:28.000000Z",
              "possui_deficiencia": "N",
              "imigrante": "N",
              "mais": [],
              "pais_nascimento": null
            }
        ]
    )
}